### ISSUE TITLE
Store samples internally

### ISSUE THREAD

**Issue by johnveitch** [johnveitch/cpnest#11]
Have the main algorithm object store its samples internally so they can be read by the application code

**Comment by wdpozzo** [comment]
I have been looking into this, but it is not clear what you mean. you want to store the whole chain for the NS in the NS class as well as the MCMC chain in the samplers?

**Comment by johnveitch** [comment]
I mean it should be possible to get the NS chain and the posterior samples from the CPNest object without writing and reading files. Should be easy to add.

**Comment by wdpozzo** [comment]
Managed to get a working version on the internal_storage branch by writing a function that returns a Live point as a structured array and merging all the structured arrays in cpnest. Not elegant, but works. Check commit 14b40c98d9a4d0f7c36afaaa9b154f62f5a5d2f1.
