### ISSUE TITLE
Add diagnostic / postprocessing script

### ISSUE THREAD

**Issue by johnveitch** [johnveitch/cpnest#13]

**Comment by johnveitch** [comment]
I added some simple plots of the nested sampling chains and histograms of posteriors if you specify verbose=2

**Comment by wdpozzo** [comment]
I did tweak the plots (see commits  df605bec5ff9bf50e57919934e40659f25ac080d and 82afc58c22ab1fe0a020242089a38d2af9f3458b ) and fixed issues with too many figures open and the corner plots. Do you think we can close this or do we want to put together an html postprocessing page?
