### ISSUE TITLE
Adding the sampled prior to the output

### ISSUE THREAD

**Issue by siyuan-chen** [johnveitch/cpnest#34]
Is it possible to add an option to create a file containing all the sampled initial prior livepoints in the output directory? This way the prior would more directly correspond to the posterior, instead of using the prior_sampling option. If I understand how cpnest works correctly: it samples the prior anyways, before it does the actual sampling process for the posterior. So being able to save the prior there, would also cut having to repeat sampling the prior separately (if eg you would like to compare the posterior to the prior in cases of non-trivial priors)
I also see that NestedSampler has options for prior_sampling and stopping. It would be great to be able call those from the CPNest object, instead of having to manually change the NestedSampler object call.

**Comment by johnveitch** [comment]
This is now possible with the prior_sampling option when setting up cpnest in v0.10.1.
