### ISSUE TITLE
How to use jump proposals?

### ISSUE THREAD

**Issue by MoritzThomasHuebner** [johnveitch/cpnest#43]
@johnveitch 
How can I use jump proposals in cpnest? What would a minimal example look like?

**Comment by MoritzThomasHuebner** [comment]
@johnveitch 
We are interested in using custom jump proposals. I implemented it myself by giving `Cpnest.__init__` a `proposals` keyword argument, that takes a dict with two proposal classes (one for the Metropolis Hastings sampler, one for the Hamiltonian Monte Carlo one). That way I can define my own jump proposals using the ones in `proposals.py` or even define my own.

**Comment by johnveitch** [comment]
OK, that sounds good. The wiring was done at the NestedSampler level but not in CPNest's top-level interface. Happy to look at a pull request for your changes.

**Comment by MoritzThomasHuebner** [comment]
@johnveitch 
https://github.com/johnveitch/cpnest/pull/44

**Comment by MoritzThomasHuebner** [comment]
@johnveitch Have you had a look at my pull request?
