### ISSUE TITLE
Failing install on python3.4

### ISSUE THREAD

**Issue by RiccardoBuscicchio** [johnveitch/cpnest#50]
Either installing from source:
```bash
python3 setup.py install --prefix=$HOME/.local
Traceback (most recent call last):
  File "setup.py", line 61, in <module>
    VERSION = VERSION_REGEX.findall(CONTENTS)[0]
TypeError: can't use a string pattern on a bytes-like object
```
or using `pip3`
```bash
 pip3 install --user cpnest
Downloading/unpacking cpnest
  Downloading cpnest-0.9.7.tar.gz (82kB): 82kB downloaded
  Running setup.py (path:/tmp/pip-build-jvz2ig73/cpnest/setup.py) egg_info for package cpnest
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip-build-jvz2ig73/cpnest/setup.py", line 49, in <module>
        VERSION = VERSION_REGEX.findall(CONTENTS)[0]
    TypeError: can't use a string pattern on a bytes-like object
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip-build-jvz2ig73/cpnest/setup.py", line 49, in <module>

    VERSION = VERSION_REGEX.findall(CONTENTS)[0]

TypeError: can't use a string pattern on a bytes-like object

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip-build-jvz2ig73/cpnest
Storing debug log for failure in /home/riccardo/.pip/pip.log
```
the installation fails under Python3.4.
However, it works on python2.7 and python >=3.6.

**Comment by mattpitkin** [comment]
Which python 3.4 version are you using? cpnest seems to install ok for me in a virtual environment running Python 3.4.5.

Generally, I recommend not using Python 3.4 and moving to a more recent version as many packages do not support 3.4 any longer (see, e.g., the latest releases of matplotlib and astropy).

**Comment by RiccardoBuscicchio** [comment]
> Which python 3.4 version are you using? cpnest seems to install ok for me in a virtual environment running Python 3.4.5.
> 
> Generally, I recommend not using Python 3.4 and moving to a more recent version as many packages do not support 3.4 any longer (see, e.g., the latest releases of matplotlib and astropy).

Thanks for checking it. I will check the cluster python3 versions available.
