### ISSUE TITLE
Cpnest stuck after populating sampler

### ISSUE THREAD

**Issue by lemnis12** [johnveitch/cpnest#74]
Hi! Since I installed cpnest, the sampler stays stuck after the populating step. So, it charges but does not seem to do anything afterward. The log file is empty, except for "2020-10-05, 20:11:52 - CPNest  : Setting verbosity to True
2020-10-05, 20:11:52 - CPNest  : Running with 1 parallel thread"

I am using cpnest 0.9.9, pyhton3.6, and my computer runs on OpenSUSE leap 15.2.

Does anyone has an idea of what happens?

**Comment by wdpozzo** [comment]
That is an indication that there might be something wrong either with the prior or the likelihood (nans or - inf), could you debug your model class getting it to print the values of prior and loglikelihood?

**Comment by lemnis12** [comment]
The priors and likelihoods do not return any nan or inf. The same code works when using another sampler (like pyMultinest for example)

**Comment by johnveitch** [comment]
Hi @lemnis12 could you check that this is still happening with v0.10.1, which is just out on conda and pip?

**Comment by lemnis12** [comment]
Hi,

Indeed, the problem seems to be solved in the newer versions.

Thank you.
