### ISSUE TITLE
Crash with verbose>=3 with python 3.9

### ISSUE THREAD

**Issue by MrTheElk** [johnveitch/cpnest#77]
While running cpnest with python 3.9, I get the error message:

  File "/usr/lib/python3.9/site-packages/cpnest/cpnest.py", line 297, in get_posterior_samples
    self.prior_samples = stack_arrays([p for p in prior_samples])
  File "<__array_function__ internals>", line 5, in stack_arrays
  File "/usr/lib/python3.9/site-packages/numpy/lib/recfunctions.py", line 1288, in stack_arrays
    dtype_l = ndtype[0]
IndexError: list index out of range

I did not get this error with python 3.8.
Setting verbose<2 bypasses this part of the code, and it exits without errors.

**Comment by MrTheElk** [comment]
Sorry, one more detail that might be useful: I installed cpnest using pip 20.2.1

**Comment by mattpitkin** [comment]
It looks like line 296 of cpnest.py needs an added if statement:

```python
if len(prior_samples) > 0:
```
which should fix this.

However, I'm not sure why it would not also be the case in Python 3.8. There must be some other issue elsewhere in the code when using Python 3.9 that causes the prior samples file to not get generated.

I'd also caution against using Python 3.9 for any analysis at the moment. Given how new it is, I expect it to be unreliable and for oddities to crop up. And cpnest in particular is not tested against Python 3.9, so who knows if you could trust the results!

**Comment by johnveitch** [comment]
Thanks for spotting this! I've pushed a fix along the lines @mattpitkin suggested.

**Comment by MrTheElk** [comment]
Thank you both for the really quick fix!
I can confirm it has solved the problem on my end.
