### ISSUE TITLE
cpnest custom logger class is set globally causing unexpected behaviour

### ISSUE THREAD

**Issue by alexlyttle** [johnveitch/cpnest#78]
When I import `cpnest` to use in another application, which also uses Python `logging`, it uses the cpnest custom logging class by default which gives unexpected output. This is because cpnest sets the Python logging class to `CPNestLogger` globally upon import. Is there anyway you can use the cpnest custom logging class only for cpnest code to avoid this issue, or just use a logging config file? Otherwise, this makes it difficult to use cpnest in other modules which also make use of logging.

## Context

We recently implemented `cpnest` in the [PBjam Python package](https://github.com/grd349/PBjam) to perform some nested sampling within a fitting function. I am currently implementing logging in PBjam, but have run into this problem. Because we import cpnest, it changes the base logging class giving unexpected behaviour. Ideally, we don't want duplicated output as seen below and if we reset the logging class then it will change how cpnest performs its logging when calling nested sampling later in the code.

## Example

```python
import logging
import cpnest

logging.basicConfig(level=logging.INFO)  # E.g. the configuration I want for the logging in my module
logger = logging.getLogger('logger_name')
logger.info('test information')

print(type(logger))
```

Outputs:

```python
2021-01-14, 14:05:57 - logger_name: test information
INFO:logger_name:test information
<class 'cpnest.logger.CPNestLogger'>
```

Whereas when I run the same code without importing cpnest I get the output:

```python
INFO:logger_name:test information
<class 'logging.Logger'>
```

## Suggestion

Use a logging config file (see [here](https://docs.python.org/3/library/logging.config.html#logging.config.fileConfig)) which can be called whenever a logger is initialised in each cpnest module, rather than using `logging.setLoggerClass` which will change the logger globally. I am happy to try implementing this myself.

**Comment by johnveitch** [comment]
Thanks for pointing this out - it's certainly an undesirable side-effect of the improvements to logging that @mj-will recently added. It seems like you have a clear idea of how to fix this, so I'd be very grateful if you're able to make a pull request.

**Comment by alexlyttle** [comment]
Thanks for the quick reply! I will take a look at this. My understanding was that subclassing `logging.Logger` as done in cpnest is good for applications where you want consistency and want to add more capability to logging, but not as good for packages where you want easy cross-compatibility between other packages.
