### ISSUE TITLE
Setuptools version 69 requires pyproject.toml

### ISSUE THREAD

**Issue by SimonMaenaut** [johnveitch/cpnest#89]
As noted in the [setuptools documentation](https://setuptools.pypa.io/en/latest/userguide/dependency_management.html) `setup_requires` in `setup.py` was deprecated and a `pyproject.toml` file is required.

In addition to
https://github.com/johnveitch/cpnest/blob/249c0e2ab4e454936edfdf2db6675bbf254a971a/setup.py#L73
and
https://github.com/johnveitch/cpnest/blob/249c0e2ab4e454936edfdf2db6675bbf254a971a/setup.cfg#L4-L6
a new `pyproject.toml` file should be added:
```toml
[build-system]
requires = ["setuptools_scm", "numpy", "cython"]
```

This made it possible to install cpnest on python 3.12 with setuptools 69.5.1 and should be compatible with older versions.

**Comment by johnveitch** [comment]
Closed by #90
