### ISSUE TITLE
Support NumPy 2.0

### ISSUE THREAD

**Issue by jakirkham** [johnveitch/cpnest#92]
NumPy is planning to release 2.0 on June 16th ( https://github.com/numpy/numpy/issues/24300#issuecomment-2125643448 ). NumPy 2.0.0 RC packages for conda & wheels came out at the beginning of April ( https://github.com/numpy/numpy/issues/24300#issuecomment-2030603395 )

NumPy has put out [a migration guide]( https://numpy.org/devdocs/numpy_2_0_migration_guide.html#numpy-2-migration-guide ). More details are in [the release notes]( https://numpy.org/devdocs/release/2.0.0-notes.html )

If CPNest makes use of NumPy's C API (and produces wheels that use it), having a release of CPNest with wheels built against NumPy 2.0.0rc1 would be helpful to ensure NumPy 1 & 2 compatible wheels (as wheels built against NumPy 1 won't be compatible with NumPy 2). More details in [this NumPy 2 ABI doc]( https://numpy.org/devdocs/dev/depending_on_numpy.html#numpy-2-abi-handling ). Note that Cython (if used) is capable of generating NumPy 2 compatible code

Also as NumPy is tracking ecosystem support for NumPy 2.0, it would be helpful to share CPNest current support status in issue (with any plans): https://github.com/numpy/numpy/issues/26191

**Comment by johnveitch** [comment]
This is fixed for release 0.11.6

**Comment by jakirkham** [comment]
Thanks John! 🙏

Would suggest always building with NumPy 2. This remains compatible with NumPy 1

So this logic...

https://github.com/johnveitch/cpnest/blob/a8fc3263eec20413a1389b8d4297ef184419bd33/pyproject.toml#L14-L15

...would be...

```diff
 [build-system]
-requires = ["setuptools_scm", "numpy", "cython"]
+requires = ["setuptools_scm", "numpy>=2", "cython"]
```

**Comment by johnveitch** [comment]
I think python<=3.9 still uses numpy<2, so will leave as-is for now.

**Comment by jakirkham** [comment]
NumPy 2 [supports Python 3.9+]( https://github.com/numpy/numpy/blob/1d49c7f7ff527c696fc26ab2278ad51632a66660/pyproject.toml#L19 )

Only Python 3.8 and earlier are limited to NumPy 1

However it looks like CPNest is on Python 3.9+. So the suggested change should be ok

https://github.com/johnveitch/cpnest/blob/a8fc3263eec20413a1389b8d4297ef184419bd33/pyproject.toml#L1-L2
